<?php
    session_start();
    unset($_SESSION['username']);
    unset($_SESSION['loggedin']);
    unset($_SESSION['usernamecheck']);
    unset($_SESSION['passwordcheck']);
    session_destroy();
    header('location:../wallpapers.php?cat=Abstract');
?>